BASE_URL = "https://dsa.ulisses-regelwiki.de/"

REQUEST_DELAY_MIN = 0.0
REQUEST_DELAY_MAX = 0.02
REQUEST_CONCURRENCY = 25
CHECKPOINT_BATCH_SIZE = 100
HTTP_404_RETRY_ATTEMPTS = 2
HTTP_404_RETRY_DELAY = 0.1

USER_AGENT = "DSA5WikiScraper/3.0 (Educational/Personal Use)"
SITEMAP_URL = BASE_URL + "sitemap.xml"
SITEMAP_INGEST_CATEGORY = "sitemap_ingest"

CATEGORIES = {
    "spells": {
        "hub_url": "zauberauswahl.html",
        "item_pattern": r"zauber\.html\?zauber=",
        "url_param": "zauber",
    },
    "cantrips": {
        "hub_url": "zaubertrickauswahl.html",
        "item_pattern": r"zaubertrick\.html\?zaubertrick=",
        "url_param": "zaubertrick",
    },
    "rituals": {
        "hub_url": "ritualauswahl.html",
        "item_pattern": r"ritual\.html\?ritual=",
        "url_param": "ritual",
    },
    "liturgies": {
        "hub_url": "liturgieauswahl.html",
        "item_pattern": r"liturgie\.html\?liturgie=",
        "url_param": "liturgie",
    },
    "ceremonies": {
        "hub_url": "zeremonieauswahl.html",
        "item_pattern": r"zeremonie\.html\?zeremonie=",
        "url_param": "zeremonie",
    },
    "blessings": {
        "hub_url": "segenauswahl.html",
        "item_pattern": r"segen\.html\?segen=",
        "url_param": "segen",
    },
    "talents": {
        "hub_url": "talentauswahl.html",
        "item_pattern": r"talent\.html\?talent=",
        "url_param": "talent",
    },
    "advantages": {
        "hub_url": "vorteilauswahl.html",
        "item_pattern": r"vorteil\.html\?vorteil=",
        "url_param": "vorteil",
    },
    "disadvantages": {
        "hub_url": "nachteilauswahl.html",
        "item_pattern": r"nachteil\.html\?nachteil=",
        "url_param": "nachteil",
    },
    "professions": {
        "hub_urls": [
            "professionen.html",
            "Pro_Geweihte.html",
            "Pro_Weltlich.html",
            "Pro_Zauberer.html",
        ],
        "item_patterns": [
            r"Gew_.*\.html",
            r"Pro_[A-Z].*\.html",
            r"profession/.*\.html",
            r"Pro_Geweihte/.*\.html",
        ],
        "url_param": "profession",
    },
    "cultures": {
        "hub_urls": [
            "kulturen.html",
            "Kul_Menschen.html",
            "Kul_Elfen.html",
            "Kul_Achaz.html",
            "Kul_Orks.html",
            "Kul_Zwerge.html",
            "Kul_SpezielleKulturen.html",
            "kulturen/goblin-kulturen.html",
            "kulturen/nachtalb-kulturen.html",
        ],
        "item_patterns": [
            r"Kul_.*\.html",
            r"kulturen/.*\.html",
        ],
        "url_param": "kultur",
    },
    "races": {
        "hub_urls": [
            "spezies.html",
            "Spez_Achaz.html",
            "Spez_Elfen.html",
            "Spez_Halbelfen.html",
            "Spez_Halborks.html",
            "Spez_Holberker.html",
            "Spez_Menschen.html",
            "Spez_Orks.html",
            "Spez_Zwerge.html",
            "spezies/goblins.html",
            "spezies/nachtalb.html",
        ],
        "item_patterns": [
            r"Spez_.*\.html",
            r"spezies/.*\.html",
        ],
        "url_param": "spezies",
    },
    "special_abilities": {
        "hub_urls": [
            "sonderfertigkeiten.html",
            "frefre.html",
            "rgergegregre.html",
            "karmale_SF.html",
            "SF_Tiere.html",
            "sf_allgemeine_sonderfertigkeiten.html",
            "Talentstilsonderfertigkeiten.html",
            "Erweiterte_Talentsonderfertigkeiten.html",
            "erw_zauber_sf_auswahl.html",
            "allgemeine_karmale_sonderfertigkeitauswahl.html",
            "animistenkraftauswahl.html",
        ],
        "item_patterns": [
            r"sf_.*\.html\?sf=",
            r"sonderfertigkeit\.html\?sf=",
            r"animistenkraft\.html\?animistenkraft=",
            r"SF_.*\.html",
            r"sf_.*\.html",
        ],
        "url_param": "sf",
    },
    "equipment": {
        "hub_urls": [
            "ruestkammer.html",
            "RK_Artefakte.html",
            "RK_Ausruestung.html",
            "RS_Helme.html",
            "RS_Ruestung.html",
            "RS_Ruestungsausruestung.html",
            "RS_Waffen.html",
            "RS_Waffenausruestung.html",
            "wunderwerke-der-mechanik.html",
        ],
        "item_patterns": [
            r"waffe\.html\?waffe=",
            r"ruestung\.html\?ruestung=",
            r"schild\.html\?schild=",
            r"gegenstand\.html\?gegenstand=",
            r"RS_.*\.html",
            r"RK_.*\.html",
            r"ausruestung/.*\.html",
            r"waffen/.*\.html",
            r"ruestung/.*\.html",
        ],
        "url_param": "item",
    },
    "creatures": {
        "hub_urls": [
            "bestiarium.html",
        ],
        "item_patterns": [
            r"bestiarium\.html\?.*=",
            r"creature\.html\?.*=",
            r"RS_.*\.html",
        ],
        "url_param": "creature",
    },
}

SKIP_PATTERNS = [
    "kontakt.html",
    "impressum",
    "datenschutz",
    "index.html",
    "start.html",
    "javascript:",
    "mailto:",
    "#",
    "suche.html",
    "sitemap",
]

PROPERTY_LABELS = [
    "Wirkung",
    "Probe",
    "AsP-Kosten",
    "Reichweite",
    "Wirkungsdauer",
    "Zauberdauer",
    "Zielkategorie",
    "Merkmal",
    "Verbreitung",
    "Steigerungsfaktor",
    "Publikation",
    "Publikationen",
    "AP-Wert",
    "Tierarten",
    "Kosten",
    "Voraussetzungen",
    "Anmerkung",
    "Errata",
    "Reversalis",
    "Zaubererweiterungen",
    "Sk",
    "LeP",
    "AuP",
    "AsP",
    "KaP",
    "RS",
    "BE",
    "GS",
    "INI",
    "AT",
    "PA",
    "TP",
    "RW",
    "Vorteil",
    "Nachteil",
    "Automatische Vor.",
    "Automatische Nach.",
    "Verbreitung",
    "Sondervorteile",
    "Rüstungsschutz",
    "Beinträchtigung",
    "Gewicht",
    "Preis",
    "TP/KK",
    "Reichweite",
    "Länge",
    "Kampftechnik",
    "Grundtalente",
    "Typus",
    "Größe",
    "LeP",
    "AuP",
    "AsP",
    "KaP",
    "MR",
    "INI",
    "GS",
    "RS/BE",
    "Aktion",
    "Anzahl",
    "AT",
    "PA",
    "TP",
    "RW",
    "Vermoeyen",
    "Besonderheiten",
    "Ausrüstung",
    "Kampfwerte",
    "Körper",
    "Geist",
    "Seele",
    "Schlechte Eigenschaften",
    "Kulturkunde",
    "Kulturtalente",
    "Kultursonderfertigkeiten",
    "Mögliche Kulturen",
    "Professionstyp",
    "Professionsvoraussetzungen",
    "Professionstalente",
    "Professionssonderfertigkeiten",
    "Kampfsonderfertigkeiten",
    "Allgemeine Sonderfertigkeiten",
    "Voraussetzungen",
    "Wirkung",
    "Tiere",
    "Unterwasser",
    "Kälte",
    "Hitze",
    "Feuer",
    "Nässe",
    "Erstickungsgefahr",
    "Haltbarkeit",
    "Schuss",
    "Ladezeiten",
    "Reichweite",
    "Waffeneigenschaften",
    "Parierwaffen",
]

HUB_LINK_THRESHOLD = 5
