EXPLICIT_HUBS = {
    "rules": [
        "alternative_regeln.html",
        "regel_erlaeuterungen.html",
        "fokusregeln-158.html",
        "grundregeln.html",
        "Regeln_Optionale.html",
    ],
    "species": [
        "spezies.html",
    ],
    "cultures": [
        "Kul_Achaz.html",
        "Kul_Elfen.html",
        "kulturen/goblin-kulturen.html",
        "Kul_Menschen.html",
        "kulturen/nachtalb-kulturen.html",
        "Kul_Orks.html",
        "Kul_SpezielleKulturen.html",
        "Kul_Zwerge.html",
    ],
    "professions": [
        "Pro_Geweihte.html",
        "Pro_Kämpfer.html",
        "Pro_Ordensleute.html",
        "Pro_Profane.html",
        "professionen/adoru-magier.html",
        "animisten.html",
        "Pro_Zauberer/brobim-geode.html",
        "Pro_Druiden.html",
        "Pro_Elfen.html",
        "Pro_Magier.html",
        "_geoden.html",
        "Pro_Hexen.html",
        "Pro_Kristallomant.html",
        "PRO_MAGIEDILETTANTEN.html",
        "Pro_Zauberer/nachtalben.html",
        "pro_Qabaloth.html",
        "pro_Runahoefundur.html",
        "PRO_SCHARLATANE.html",
        "schelme.html",
        "za.html",
        "ZB.html",
        "PRO_ZAUBERTAENZER.html",
        "Zibilja.html",
    ],
    "special_abilities_karmale": [
        "allgemeine_karmale_sonderfertigkeitauswahl.html",
        "erweiterte_liturgiestilsonderfertigkeitenauswahl.html",
        "karmale_traditionauswahl.html",
        "liturgiestilsonderfertigkeitenauswahl.html",
        "predigtauswahl.html",
        "visionauswahl.html",
        "zeremonialgegenstands_sf_auswahl.html",
    ],
    "special_abilities_magical": [
        "allgemeine_magische_sonderfertigkeitauswahl.html",
        "erw_zauber_sf_auswahl.html",
        "msf_Homunculusfaehigkeiten.html",
        "lykanthropische-gaben.html",
        "magische_traditionauswahl.html",
        "Daemonenpakt.html",
        "SF_Paktgeschenke-Elementar.html",
        "Feenpakt.html",
        "sikaryan-raub-sonderfertigkeiten.html",
        "traditionsartefakt_sf_auswahl.html",
        "VampirischeGaben.html",
        "zauberstil_sf_auswahl.html",
        "Ahnenzeichen.html",
        "mSF-AlhanischeZauberzeichen.html",
        "mSF_Zauberzeichen_Arkanoglyphen.html",
        "bannundschutz.html",
        "mSF_Zauberzeichen_Arkanoglyphen-Zusatzzeichen.html",
    ],
    "special_abilities_profane": [
        "sf_allgemeine_sonderfertigkeiten.html",
        "Befehls_SF.html",
        "Erweiterte_Talentsonderfertigkeiten.html",
        "SF_Erweitertekampfstilsonderfertigkeiten.html",
        "sf_kampfsonderfertigkeiten.html",
        "SF_Kampfstilsonderfertigkeiten/unbewaffnete-kampfstile.html",
        "SF_Kampfstilsonderfertigkeiten/bewaffnete-kampfstile.html",
        "SF_Pruegelsonderfertigkeiten.html",
        "SF_Schick.html",
        "Sprachen.html",
        "Talentstilsonderfertigkeiten.html",
    ],
    "special_abilities_animal": [
        "TSF_Ausbildungsaufs%C3%A4tze.html",
        "sf_homunculus.html",
        "TSF_Kampfsonderfertigkeiten.html",
        "SF_Tiersonderfertigkeiten.html",
        "TSF_Tricks.html",
        "VSF_Vertrautentricks.html",
    ],
    "advantages": [
        "vorteilauswahl.html",
    ],
    "advantages_animal": [
        "vor-und-nachteile/tiervor-und-nachteile/vorteile-tiere.html",
    ],
    "disadvantages": [
        "nachteilauswahl.html",
    ],
    "disadvantages_animal": [
        "vor-und-nachteile/tiervor-und-nachteile/nachteile-tiere.html",
    ],
    "magic": [
        "animistenkraftauswahl.html",
        "Z_MH_Bannzeichen.html",
        "elfenliedauswahl.html",
        "MH_Goblinrituale.html",
        "geodenritualauswahl.html",
        "hexenfluchauswahl.html",
        "herrschaftsritualauswahl.html",
        "schelmenstreichauswahl.html",
        "verzerrte_elfenliedauswahl.html",
        "zauberruneauswahl.html",
        "zaubertanzauswahl.html",
        "zaubermelodieauswahl.html",
        "zibiljaritualauswahl.html",
    ],
    "götterwirken": [
        "liturgieauswahl.html",
        "segenauswahl.html",
        "talisman_karmal_auswahl.html",
        "zeremonieauswahl.html",
    ],
    "ruestkammer_artifacts": [
        "wunderwerke-der-mechanik.html",
        "RK_Artefakte/magische-artefakte.html",
        "Artefakte.html",
    ],
    "ruestkammer_equipment": [
        "RK_Ausruestung.html",
    ],
    "ruestkammer_helmets": [
        "RS_Helme.html",
    ],
    "ruestkammer_armor_equipment": [
        "RS_Ruestungsausstattung.html",
    ],
    "ruestkammer_armor": [
        "RS_Ruestung.html",
        "ruestungen.html",
    ],
    "ruestkammer_weapons": [
        "RS_Waffen.html",
        "RS_Waffenausruestung.html",
    ],
    "bestiarium": [
        "bestiarium.html",
        "Best_Chimären.html",
        "Best_Drachen.html",
        "Best_Daimonide.html",
        "Best_Dämonen.html",
        "Elementare.html",
        "Best_Feen.html",
        "Best_Golemiden.html",
        "geister.html",
        "Best_Golems.html",
        "best_Homunculi.html",
        "Best_Kulturschaffende.html",
        "Best-Typus_Pflanzen.html",
        "Best_Untote.html",
        "Best_Tiere.html",
        "Best_Uebernatürliche_Wesen.html",
    ],
    "herbarium": [
        "her_Pflanzen.html",
        "her_rezepte.html",
    ],
    "poisons_and_illnesses": [
        "GR_Krankheiten.html",
        "GR_Gifte.html",
    ],
}
